# Generated by Django 4.2.3 on 2023-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_ispricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
