# Generated by Django 4.2.3 on 2023-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer_id',
            field=models.IntegerField(null=True),
        ),
    ]
